version: '3.8'

services:
  db:
    image: mariadb:10.4
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - /home/reilly/Services/LamingtonDB:/var/lib/mysql
      # - db:/var/lib/mysql
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: ./.env
    network_mode: service:db
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mariadb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true

# volumes: 
#   db:
