version: "3.8"

services:
    lamington_server:
        image: lamington_server:latest
        container_name: lamington_server
        depends_on:
            - mariadb
        build: .
        restart: unless-stopped
        env_file: .env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - DB_USER=$DB_USER
            - DB_PASSWORD=$DB_PASSWORD
            - DB_NAME=$DB_NAME
            - DB_PORT=$DB_DOCKER_PORT
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        networks:
            - lamington-network
    mariadb:
        image: mariadb:10.4
        container_name: mariadb
        restart: unless-stopped
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
            - MYSQL_DATABASE=$DB_NAME
        ports:
            - $DB_LOCAL_PORT:$DB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
            - ./database/schema:/docker-entrypoint-initdb.d/:ro
        networks:
            - lamington-network
volumes:
    db:
    node_modules:

networks:
    lamington-network:
        driver: bridge
