version: "3.8"

services:
    lamington_server:
        image: lamington_server:latest
        container_name: lamington_server
        depends_on:
            - db_production
        build: .
        restart: unless-stopped
        env_file: .env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        networks:
            - lamington-network

    db_production:
        image: postgres:latest
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_USER=$DB_PROD_USER
            - POSTGRES_DB=$DB_PROD_NAME
            - POSTGRES_PASSWORD=$DB_PROD_PASSWORD
        expose:
            - $DB_PORT
        volumes:
            - db_production:/var/lib/postgresql/data
        networks:
            - lamington-network
volumes:
    db_production:

networks:
    lamington-network:
        driver: bridge
