/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/cooklist/meals": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get cook list meals */
        readonly get: operations["getCookList"];
        readonly put?: never;
        /** Add meal to cook list */
        readonly post: operations["postCookList"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/cooklist/meals/{mealId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly mealId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /** Remove meal from cook list */
        readonly delete: operations["deleteCookList"];
        readonly options?: never;
        readonly head?: never;
        /** Update meal in cook list */
        readonly patch: operations["putCookList"];
        readonly trace?: never;
    };
    readonly "/meals/{mealId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly mealId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        /** Get a meal by ID */
        readonly get: operations["getMeal"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/planners": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get user planners */
        readonly get: operations["getPlanners"];
        readonly put?: never;
        /** Create a planner */
        readonly post: operations["postPlanner"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        /** Get a planner */
        readonly get: operations["getPlanner"];
        readonly put?: never;
        readonly post?: never;
        /** Delete a planner */
        readonly delete: operations["deletePlanner"];
        readonly options?: never;
        readonly head?: never;
        /** Update a planner */
        readonly patch: operations["putPlanner"];
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}/meals": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Add a meal to a planner */
        readonly post: operations["postPlannerMeal"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}/meals/{year}/{month}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
                readonly year: components["schemas"]["Year"];
                readonly month: components["schemas"]["Month"];
            };
            readonly cookie?: never;
        };
        /** Get planner meals */
        readonly get: operations["getPlannerMeals"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}/meals/{mealId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
                readonly mealId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /** Remove a meal from a planner */
        readonly delete: operations["deletePlannerMeal"];
        readonly options?: never;
        readonly head?: never;
        /** Update a meal in a planner */
        readonly patch: operations["putPlannerMeal"];
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}/members": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        /** Get planner members */
        readonly get: operations["getPlannerMembers"];
        readonly put?: never;
        /** Invite a member to a planner */
        readonly post: operations["postPlannerMember"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}/members/{userId}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
                readonly userId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /** Remove a member from a planner */
        readonly delete: operations["deletePlannerMember"];
        readonly options?: never;
        readonly head?: never;
        /** Update a planner member */
        readonly patch: operations["updatePlannerMember"];
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}/invite/accept": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Accept planner invitation */
        readonly post: operations["acceptPlannerInvite"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}/invite/decline": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Decline planner invitation */
        readonly post: operations["declinePlannerInvite"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/planners/{plannerId}/leave": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Leave a planner */
        readonly post: operations["leavePlanner"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/extractor/recipeMetadata": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Extract recipe metadata */
        readonly get: operations["getExtractRecipeMetadata"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/extractor/recipe": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Extract full recipe */
        readonly get: operations["getExtractRecipe"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly ErrorResponse: {
            /** @example true */
            readonly error: boolean;
            readonly message?: string;
        };
        readonly Owner: {
            readonly userId: string;
            readonly firstName: string;
        };
        /** Format: uuid */
        readonly Uuid: string;
        readonly Year: number;
        readonly Month: number;
        readonly DayOfMonth: number;
        /**
         * @description * `O` - Owner * `A` - Administrator * `M` - Member * `P` - Pending * `B` - Blocked
         * @enum {string}
         */
        readonly UserStatus: "O" | "A" | "M" | "P" | "B";
        /** @enum {string} */
        readonly Course: "breakfast" | "lunch" | "dinner";
        readonly MealProperties: {
            readonly mealId?: components["schemas"]["Uuid"];
            readonly plannerId?: components["schemas"]["Uuid"];
            readonly year?: components["schemas"]["Year"];
            readonly month?: components["schemas"]["Month"];
            readonly dayOfMonth?: components["schemas"]["DayOfMonth"];
            readonly course?: components["schemas"]["Course"];
            readonly description?: string;
            readonly source?: string;
            readonly sequence?: number;
            readonly recipeId?: components["schemas"]["Uuid"];
            readonly notes?: string;
        };
        readonly Meal: WithRequired<components["schemas"]["MealProperties"], "mealId" | "course"> & {
            readonly owner: components["schemas"]["Owner"];
            readonly heroImage?: components["schemas"]["ImageAttachment"];
        };
        readonly MealBase: {
            readonly course: components["schemas"]["Course"];
            readonly description?: string;
            readonly source?: string;
            readonly recipeId?: components["schemas"]["Uuid"];
            readonly heroImage?: components["schemas"]["ImageAttachment"];
        };
        readonly MealCreateBase: {
            readonly course: components["schemas"]["Course"];
            readonly description?: string | null;
            readonly source?: string | null;
            readonly recipeId?: components["schemas"]["Uuid"] | null;
            readonly heroImage?: string;
        };
        readonly MealUpdateBase: {
            readonly course?: components["schemas"]["Course"];
            readonly description?: string | null;
            readonly source?: string | null;
            readonly recipeId?: components["schemas"]["Uuid"] | null;
            readonly heroImage?: string | null;
        };
        readonly CookListMeal: components["schemas"]["MealBase"] & {
            readonly mealId: components["schemas"]["Uuid"];
            readonly owner: components["schemas"]["Owner"];
            readonly sequence?: number;
        };
        readonly CookListMealCreate: components["schemas"]["MealCreateBase"] & {
            readonly sequence?: number | null;
        };
        readonly CookListMealUpdate: components["schemas"]["MealUpdateBase"] & {
            readonly sequence?: number | null;
        };
        readonly Planner: {
            readonly plannerId: components["schemas"]["Uuid"];
            readonly owner: components["schemas"]["Owner"];
            readonly name: string;
            readonly color?: string;
            readonly description?: string;
            readonly status?: components["schemas"]["UserStatus"];
        };
        readonly PlannerCreate: {
            readonly name: string;
            readonly color?: string;
            readonly description?: string | null;
        };
        readonly PlannerUpdate: {
            readonly name?: string;
            readonly color?: string;
            readonly description?: string | null;
        };
        readonly PlannerMember: {
            readonly userId: components["schemas"]["Uuid"];
            readonly firstName: string;
            readonly lastName?: string;
            readonly status?: components["schemas"]["UserStatus"];
        };
        readonly PlannerMemberUpdate: {
            readonly status: components["schemas"]["UserStatus"];
        };
        readonly PlannerMemberCreate: {
            readonly userId: string;
        };
        readonly PlannerMeal: components["schemas"]["MealBase"] & {
            readonly mealId: components["schemas"]["Uuid"];
            readonly plannerId: components["schemas"]["Uuid"];
            readonly owner: components["schemas"]["Owner"];
            readonly year: components["schemas"]["Year"];
            readonly month: components["schemas"]["Month"];
            readonly dayOfMonth: components["schemas"]["DayOfMonth"];
        };
        readonly PlannerMealCreate: components["schemas"]["MealCreateBase"] & {
            readonly year: components["schemas"]["Year"];
            readonly month: components["schemas"]["Month"];
            readonly dayOfMonth: components["schemas"]["DayOfMonth"];
        };
        readonly PlannerMealUpdate: components["schemas"]["MealUpdateBase"] & {
            readonly year?: components["schemas"]["Year"];
            readonly month?: components["schemas"]["Month"];
            readonly dayOfMonth?: components["schemas"]["DayOfMonth"];
        };
        readonly MealPartial: components["schemas"]["MealProperties"];
        readonly MealCreate: WithRequired<components["schemas"]["MealProperties"], "course">;
        readonly ExtractedRecipeMetadata: {
            readonly name: string;
            readonly imageUrl?: string;
        };
        readonly RecipeBase: {
            readonly description?: string;
            readonly prepTime?: number;
            readonly cookTime?: number;
            readonly source?: string;
            readonly url?: string;
            readonly notes?: string;
        };
        readonly ExtractedRecipe: components["schemas"]["ExtractedRecipeMetadata"] & components["schemas"]["RecipeBase"];
        readonly Recipe: components["schemas"]["ExtractedRecipe"] & {
            readonly recipeId?: components["schemas"]["Uuid"];
            readonly public?: boolean;
            readonly timesCooked?: number;
            readonly owner?: components["schemas"]["Owner"];
        };
        readonly ImageAttachment: {
            readonly attachmentId: components["schemas"]["Uuid"];
            readonly uri: string;
        };
    };
    responses: {
        /** @description Bad Request */
        readonly BadRequest: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not Found */
        readonly NotFound: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal Server Error */
        readonly InternalServerError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly getCookList: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["CookListMeal"][];
                };
            };
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly postCookList: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CookListMealCreate"] | readonly components["schemas"]["CookListMealCreate"][];
            };
        };
        readonly responses: {
            /** @description Created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["CookListMeal"][];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly deleteCookList: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly mealId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Deleted */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly putCookList: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly mealId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CookListMealUpdate"];
            };
        };
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CookListMeal"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly getMeal: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly mealId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Meal"];
                };
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly getPlanners: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["Planner"][];
                };
            };
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly postPlanner: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PlannerCreate"];
            };
        };
        readonly responses: {
            /** @description Created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Planner"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly getPlanner: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Planner"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly deletePlanner: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly putPlanner: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PlannerUpdate"];
            };
        };
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Planner"];
                };
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly postPlannerMeal: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PlannerMealCreate"] | readonly components["schemas"]["PlannerMealCreate"][];
            };
        };
        readonly responses: {
            /** @description Created */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["PlannerMeal"][];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly getPlannerMeals: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
                readonly year: components["schemas"]["Year"];
                readonly month: components["schemas"]["Month"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["PlannerMeal"][];
                };
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly deletePlannerMeal: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
                readonly mealId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly putPlannerMeal: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
                readonly mealId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PlannerMealUpdate"];
            };
        };
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PlannerMeal"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly getPlannerMembers: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["PlannerMember"][];
                };
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly postPlannerMember: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PlannerMemberCreate"];
            };
        };
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly deletePlannerMember: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
                readonly userId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly updatePlannerMember: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
                readonly userId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PlannerMemberUpdate"];
            };
        };
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PlannerMember"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly acceptPlannerInvite: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly declinePlannerInvite: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly leavePlanner: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly plannerId: components["schemas"]["Uuid"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No Content */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly getExtractRecipeMetadata: {
        readonly parameters: {
            readonly query: {
                /** @description The URL of the recipe to extract metadata from */
                readonly url: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ExtractedRecipeMetadata"];
                };
            };
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly getExtractRecipe: {
        readonly parameters: {
            readonly query: {
                /** @description The URL of the recipe to extract */
                readonly url: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ExtractedRecipe"];
                };
            };
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
