version: "3.5"

name: "lamington-server"
services:
    app:
        image: app:latest
        depends_on:
            - db_production
            - db_development
            - db_testing
        build: .
        restart: unless-stopped
        env_file: .env
        ports:
            - $NODE_LCOAL_PORT:$NODE_DOCKER_PORT
        volumes:
            - ..:/workspace:cached
        stdin_open: true
        tty: true

    db_production:
        image: postgres:latest
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_USER=$DB_PROD_USER
            - POSTGRES_DB=$DB_PROD_NAME
            - POSTGRES_PASSWORD=$DB_PROD_PASSWORD
        expose:
            - $DB_PORT
        volumes:
            - db_production:/var/lib/postgresql/data

    db_development:
        image: postgres:latest
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_USER=$DB_DEV_USER
            - POSTGRES_DB=$DB_DEV_NAME
            - POSTGRES_PASSWORD=$DB_DEV_PASSWORD
        expose:
            - $DB_PORT
        volumes:
            - db_development:/var/lib/postgresql/data

    db_testing:
        image: postgres:latest
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_USER=$DB_TEST_USER
            - POSTGRES_DB=$DB_TEST_NAME
            - POSTGRES_PASSWORD=$DB_TEST_PASSWORD
        expose:
            - $DB_PORT
        volumes:
            - db_testing:/var/lib/postgresql/data

volumes:
    db_production:
    db_development:
    db_testing:
