version: "3.5"

name: "lamington-server"
services:
    mariadb:
        image: mariadb:10.4
        restart: unless-stopped
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
            - MYSQL_DATABASE=$DB_NAME
        ports:
            - $DB_LOCAL_PORT:$DB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql

    mariadb_testdb:
        image: mariadb:10.4
        restart: unless-stopped
        env_file: .env
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
            - MYSQL_DATABASE=$DB_NAME
        ports:
            - $DB_TEST_LOCAL_PORT:$DB_TEST_DOCKER_PORT
        volumes:
            - db_test:/var/lib/mysql
            - ../database/schema:/docker-entrypoint-initdb.d/:ro

    app:
        image: app:latest
        depends_on:
            - mariadb
        build: .
        restart: unless-stopped
        env_file: .env
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        volumes:
            - ..:/workspace:cached
        environment:
            - DB_HOST=mariadb
            - DB_USER=$DB_USER
            - DB_PASSWORD=$DB_PASSWORD
            - DB_NAME=$DB_NAME
            - DB_PORT=$DB_DOCKER_PORT
        stdin_open: true
        tty: true

volumes:
    db:
    db_test:
