version: "3.5"

name: "lamington-server"
services:
    app:
        image: app:latest
        depends_on:
            - db_development
            - db_testing
        build: .
        restart: unless-stopped
        env_file: .env
        ports:
            - $PORT:$PORT
        volumes:
            - ..:/workspace:cached
        stdin_open: true
        tty: true

    db_development:
        image: postgres:16.4
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_USER=$DB_DEV_USER
            - POSTGRES_DB=$DB_DEV_NAME
            - POSTGRES_PASSWORD=$DB_DEV_PASSWORD
            - PGPORT=$DB_PORT
        expose:
            - $DB_PORT
        volumes:
            - db_development:/var/lib/postgresql/data

    db_testing:
        image: postgres:16.4
        restart: unless-stopped
        env_file: .env
        environment:
            - POSTGRES_USER=$DB_TEST_USER
            - POSTGRES_DB=$DB_TEST_NAME
            - POSTGRES_PASSWORD=$DB_TEST_PASSWORD
            - PGPORT=$DB_PORT
        expose:
            - $DB_PORT
        volumes:
            - db_testing:/var/lib/postgresql/data

volumes:
    db_development:
    db_testing:
