export const MAX_EXTRACTED_SECTIONS = 10;
export const MAX_INGREDIENTS_PER_SECTION = 50;
export const MAX_EXTRACTED_INGREDIENTS =
    MAX_EXTRACTED_SECTIONS * MAX_INGREDIENTS_PER_SECTION;
export const MAX_INGREDIENT_TEXT_LENGTH = 1_024;
export const MAX_INGREDIENT_NAME_LENGTH = 255;
export const MAX_INGREDIENT_PREPARATION_LENGTH = 255;
export const MAX_AMOUNT_VALUE_LENGTH = 4;
export const MAX_METHOD_ITEMS_PER_SECTION = 50;
export const MAX_METHOD_ITEMS =
    MAX_EXTRACTED_SECTIONS * MAX_METHOD_ITEMS_PER_SECTION;
export const MAX_METHOD_TEXT_LENGTH = 4_096;
export const MAX_SECTION_NAME_LENGTH = 255;
export const MAX_EXTRACTED_NAME_LENGTH = 255;
export const MAX_EXTRACTED_SOURCE_LENGTH = 255;
export const MAX_EXTRACTED_SUMMARY_LENGTH = 4_096;
export const MAX_IMAGES = 100;
export const MAX_TAG_CANDIDATES = 1_000;
export const MAX_RECIPE_GRAPH_NODES = 1_000;
export const MAX_RECIPE_GRAPH_DEPTH = 50;
export const MAX_MATCH_CANDIDATES = 5_000;
export const MAX_MATCH_WORK = 1_000_000;
